BEGIN;

CREATE TYPE public.match_run_status AS ENUM ('running', 'completed', 'failed');

CREATE TABLE public.match_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  status public.match_run_status NOT NULL DEFAULT 'running',
  jobs_found INT DEFAULT 0,
  new_jobs_count INT DEFAULT 0,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.match_runs IS 'Tracks user-triggered job matching runs';

ALTER TABLE public.match_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own match runs"
  ON public.match_runs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own match runs"
  ON public.match_runs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_match_runs_user_id ON public.match_runs(user_id);
CREATE INDEX idx_match_runs_created_at ON public.match_runs(created_at DESC);
CREATE INDEX idx_match_runs_user_latest
  ON public.match_runs(user_id, created_at DESC);

COMMIT;
