BEGIN;

CREATE TYPE public.user_offer_status AS ENUM ('inbox', 'saved', 'archived');

COMMENT ON TYPE public.user_offer_status IS 'Status tracking for user-job relationships: inbox (new matches), saved (bookmarked), archived (dismissed)';

CREATE TABLE public.user_offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  offer_id BIGINT NOT NULL REFERENCES public.offers(id) ON DELETE CASCADE,
  status public.user_offer_status NOT NULL DEFAULT 'inbox',
  similarity_score FLOAT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, offer_id)
);

COMMENT ON TABLE public.user_offers IS 'Tracks user-job relationships with AI similarity scores. Links users to matched job offers with status (inbox/saved/archived).';
COMMENT ON COLUMN public.user_offers.user_id IS 'Foreign key to auth.users - the user who has this relationship with the offer';
COMMENT ON COLUMN public.user_offers.offer_id IS 'Foreign key to offers - the job offer in this relationship';
COMMENT ON COLUMN public.user_offers.status IS 'Current status: inbox (newly matched), saved (bookmarked for later), archived (dismissed)';
COMMENT ON COLUMN public.user_offers.similarity_score IS 'AI-computed cosine similarity score (0.7-1.0) between user profile and job offer embeddings';

ALTER TABLE public.user_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own offers"
  ON public.user_offers FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own offers"
  ON public.user_offers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own offers"
  ON public.user_offers FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own offers"
  ON public.user_offers FOR DELETE
  USING (auth.uid() = user_id);

CREATE INDEX idx_user_offers_user_id ON public.user_offers(user_id);
CREATE INDEX idx_user_offers_status ON public.user_offers(status);
CREATE INDEX idx_user_offers_user_status ON public.user_offers(user_id, status);
CREATE INDEX idx_user_offers_created_at ON public.user_offers(created_at DESC);
CREATE INDEX idx_user_offers_similarity_score ON public.user_offers(user_id, similarity_score DESC);

COMMENT ON INDEX idx_user_offers_user_id IS 'Fast lookup of all offers for a specific user';
COMMENT ON INDEX idx_user_offers_status IS 'Fast filtering by status across all users';
COMMENT ON INDEX idx_user_offers_user_status IS 'Composite index for filtering user offers by status (e.g., inbox view)';
COMMENT ON INDEX idx_user_offers_created_at IS 'Ordering offers by when they were matched (newest first)';
COMMENT ON INDEX idx_user_offers_similarity_score IS 'Ordering offers by relevance score for a user';

CREATE TRIGGER set_user_offers_updated_at
  BEFORE UPDATE ON public.user_offers
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

COMMIT;
