-- ====================================================================
-- Create Dismissed Offers Table
-- Version: 1.0
-- Description: Tracks permanently dismissed job offers to prevent
--              them from reappearing in future matches (soft delete)
-- ====================================================================

BEGIN;

-- ====================================================================
-- SECTION 1: Create dismissed_offers table
-- ====================================================================

CREATE TABLE public.dismissed_offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  offer_id BIGINT NOT NULL REFERENCES public.offers(id) ON DELETE CASCADE,
  dismissed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, offer_id)
);

COMMENT ON TABLE public.dismissed_offers IS
  'Tracks permanently dismissed job offers to prevent them from reappearing in future matches';
COMMENT ON COLUMN public.dismissed_offers.user_id IS
  'Foreign key to auth.users - the user who dismissed this offer';
COMMENT ON COLUMN public.dismissed_offers.offer_id IS
  'Foreign key to offers - the job offer that was dismissed';
COMMENT ON COLUMN public.dismissed_offers.dismissed_at IS
  'Timestamp when the offer was dismissed';

-- ====================================================================
-- SECTION 2: Enable Row Level Security
-- ====================================================================

ALTER TABLE public.dismissed_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own dismissed offers"
  ON public.dismissed_offers FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own dismissed offers"
  ON public.dismissed_offers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own dismissed offers"
  ON public.dismissed_offers FOR DELETE
  USING (auth.uid() = user_id);

-- ====================================================================
-- SECTION 3: Create indexes for performance
-- ====================================================================

CREATE INDEX idx_dismissed_offers_user_id ON public.dismissed_offers(user_id);
CREATE INDEX idx_dismissed_offers_user_offer ON public.dismissed_offers(user_id, offer_id);

COMMENT ON INDEX idx_dismissed_offers_user_id IS
  'Fast lookup of all dismissed offers for a specific user';
COMMENT ON INDEX idx_dismissed_offers_user_offer IS
  'Composite index for checking if specific offer is dismissed by user';

COMMIT;
