import type { JustJoinItTechnology } from "../types/just-join-it";
import type { NoFluffJobsCategory } from "../types/no-fluff-jobs";

const SKILL_TO_NFJ_CATEGORY: Record<string, NoFluffJobsCategory> = {
  react: "frontend",
  typescript: "frontend",
  javascript: "frontend",
  html: "frontend",
  css: "frontend",
  tailwindcss: "frontend",
  "tailwind css": "frontend",
  sass: "frontend",
  scss: "frontend",
  bootstrap: "frontend",
  vue: "frontend",
  "vue.js": "frontend",
  angular: "frontend",
  svelte: "frontend",
  redux: "frontend",
  webpack: "frontend",
  vite: "frontend",
  jquery: "frontend",

  "node.js": "backend",
  nodejs: "backend",
  express: "backend",
  nestjs: "backend",
  deno: "backend",
  django: "backend",
  flask: "backend",
  fastapi: "backend",
  spring: "backend",
  "spring boot": "backend",
  hibernate: "backend",
  laravel: "backend",
  symfony: "backend",
  rails: "backend",
  "ruby on rails": "backend",
  graphql: "backend",
  php: "backend",
  ruby: "backend",
  python: "backend",
  java: "backend",
  "c#": "backend",
  csharp: "backend",
  ".net": "backend",
  dotnet: "backend",
  "asp.net": "backend",
  blazor: "backend",
  go: "backend",
  golang: "backend",
  scala: "backend",
  akka: "backend",
  kotlin: "backend",
  c: "backend",
  "c++": "backend",
  cpp: "backend",
  rust: "backend",

  nextjs: "fullstack",
  "next.js": "fullstack",
  nuxtjs: "fullstack",
  "nuxt.js": "fullstack",

  swift: "mobile",
  "react native": "mobile",
  flutter: "mobile",
  dart: "mobile",
  android: "mobile",
  ios: "mobile",

  selenium: "testing",
  cypress: "testing",
  playwright: "testing",
  jest: "testing",

  docker: "devops",
  kubernetes: "devops",
  k8s: "devops",
  terraform: "devops",
  ansible: "devops",
  jenkins: "devops",
  ci: "devops",
  cd: "devops",
  aws: "devops",
  azure: "devops",
  gcp: "devops",
  "google cloud": "devops",
  linux: "devops",
  nginx: "devops",

  figma: "ux",
  sketch: "ux",
  "adobe xd": "ux",

  sql: "data",
  postgresql: "data",
  postgres: "data",
  mongodb: "data",
  mysql: "data",
  redis: "data",
  elasticsearch: "data",
  cassandra: "data",
  bigquery: "data",
  spark: "data",
  kafka: "data",

  tensorflow: "ai-ml",
  pytorch: "ai-ml",
  "machine learning": "ai-ml",
  ml: "ai-ml",
  openai: "ai-ml",
  llm: "ai-ml",
};

const SKILL_TO_CATEGORY: Record<string, JustJoinItTechnology> = {
  react: "javascript",
  typescript: "javascript",
  javascript: "javascript",
  nextjs: "javascript",
  "next.js": "javascript",
  nuxtjs: "javascript",
  "nuxt.js": "javascript",
  vue: "javascript",
  "vue.js": "javascript",
  angular: "javascript",
  svelte: "javascript",
  "node.js": "javascript",
  nodejs: "javascript",
  express: "javascript",
  nestjs: "javascript",
  deno: "javascript",
  jquery: "javascript",
  redux: "javascript",
  graphql: "javascript",
  html: "html",
  css: "html",
  tailwindcss: "html",
  "tailwind css": "html",
  sass: "html",
  scss: "html",
  bootstrap: "html",
  webpack: "html",
  vite: "html",
  python: "python",
  django: "python",
  flask: "python",
  fastapi: "python",
  pandas: "python",
  numpy: "python",
  java: "java",
  spring: "java",
  "spring boot": "java",
  hibernate: "java",
  maven: "java",
  gradle: "java",
  kotlin: "java",
  "c#": "net",
  csharp: "net",
  ".net": "net",
  dotnet: "net",
  "asp.net": "net",
  blazor: "net",
  ruby: "ruby",
  rails: "ruby",
  "ruby on rails": "ruby",
  go: "go",
  golang: "go",
  php: "php",
  laravel: "php",
  symfony: "php",
  wordpress: "php",
  scala: "scala",
  akka: "scala",
  c: "c",
  "c++": "c",
  cpp: "c",
  rust: "c",
  swift: "mobile",
  "react native": "mobile",
  flutter: "mobile",
  dart: "mobile",
  android: "mobile",
  ios: "mobile",
  selenium: "testing",
  cypress: "testing",
  playwright: "testing",
  jest: "testing",
  docker: "devops",
  kubernetes: "devops",
  k8s: "devops",
  terraform: "devops",
  ansible: "devops",
  jenkins: "devops",
  ci: "devops",
  cd: "devops",
  aws: "devops",
  azure: "devops",
  gcp: "devops",
  "google cloud": "devops",
  linux: "admin",
  nginx: "admin",
  figma: "ux",
  sketch: "ux",
  "adobe xd": "ux",
  sql: "data",
  postgresql: "data",
  postgres: "data",
  mongodb: "data",
  mysql: "data",
  redis: "data",
  elasticsearch: "data",
  cassandra: "data",
  bigquery: "data",
  spark: "data",
  kafka: "data",
  tensorflow: "ai",
  pytorch: "ai",
  "machine learning": "ai",
  ml: "ai",
  openai: "ai",
  llm: "ai",
};

export function mapSkillsToCategories(
  skills: string[]
): JustJoinItTechnology[] {
  const categories = new Set<JustJoinItTechnology>();

  for (const skill of skills) {
    const normalized = skill.toLowerCase().trim();
    const category = SKILL_TO_CATEGORY[normalized];
    if (category) {
      categories.add(category);
    }
  }

  return Array.from(categories);
}

export function mapSkillsToNoFluffJobsCategories(
  skills: string[]
): NoFluffJobsCategory[] {
  const categories = new Set<NoFluffJobsCategory>();

  for (const skill of skills) {
    const normalized = skill.toLowerCase().trim();
    const category = SKILL_TO_NFJ_CATEGORY[normalized];
    if (category) {
      categories.add(category);
    }
  }

  return Array.from(categories);
}
